BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-vek280"
BBFILE_PATTERN_meta-vek280 = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-vek280 = "6"

LAYERDEPENDS_meta-vek280 = "core"
LAYERSERIES_COMPAT_meta-vek280 = "scarthgap"
