#!/bin/bash

# This file is automatically generated using the do script
ABS_PATH=$(pwd)
export PROJECT_NAME=example_design


echo '# Software platform generation ...'
cd $ABS_PATH/
mkdir -p a70/xrt/image >> $ABS_PATH/cmd.log
# xsct is disabled in Vitis 2026.1; use the Vitis Python CLI instead.
vitis -s gen_xpfm.py linux >> $ABS_PATH/cmd.log
if [ $? != 0 ]; then tail $ABS_PATH/cmd.log && exit 1; fi
echo '# BIF ...'
cd $ABS_PATH/
cp -f $ABS_PATH/../sw/petalinux/images/linux/u-boot.elf     $ABS_PATH/xpfm/${PROJECT_NAME}_pfm/export/${PROJECT_NAME}_pfm/sw/ >> $ABS_PATH/cmd.log
cp -f $ABS_PATH/../sw/petalinux/images/linux/system.dtb     $ABS_PATH/xpfm/${PROJECT_NAME}_pfm/export/${PROJECT_NAME}_pfm/sw/ >> $ABS_PATH/cmd.log
cp -f $ABS_PATH/../sw/petalinux/images/linux/bl31.elf       $ABS_PATH/xpfm/${PROJECT_NAME}_pfm/export/${PROJECT_NAME}_pfm/sw/ >> $ABS_PATH/cmd.log
cp -f $ABS_PATH/../sw/petalinux/images/linux/Image       $ABS_PATH/xpfm/${PROJECT_NAME}_pfm/export/${PROJECT_NAME}_pfm/sw/ >> $ABS_PATH/cmd.log
#cp -f $ABS_PATH/../sw/petalinux/images/linux/rootfs.tar.gz  $ABS_PATH/xpfm/${PROJECT_NAME}_pfm/export/${PROJECT_NAME}_pfm/sw/ >> $ABS_PATH/cmd.log
cp -f $ABS_PATH/../sw/petalinux/images/linux/rootfs.ext4  $ABS_PATH/xpfm/${PROJECT_NAME}_pfm/export/${PROJECT_NAME}_pfm/sw/ >> $ABS_PATH/cmd.log
mkdir -p $ABS_PATH/xpfm/${PROJECT_NAME}_pfm/export/${PROJECT_NAME}_pfm/sw/${PROJECT_NAME}_pfm/xrt/image/ >> $ABS_PATH/cmd.log
# boot.scr is no longer in images/linux in 2026.1; fall back to pre-built.
[ -f $ABS_PATH/../sw/petalinux/images/linux/boot.scr ] && \
    cp -f $ABS_PATH/../sw/petalinux/images/linux/boot.scr $ABS_PATH/xpfm/${PROJECT_NAME}_pfm/export/${PROJECT_NAME}_pfm/sw/${PROJECT_NAME}_pfm/xrt/image/ >> $ABS_PATH/cmd.log || \
    cp -f $ABS_PATH/../sw/petalinux/pre-built/linux/images/boot.scr $ABS_PATH/xpfm/${PROJECT_NAME}_pfm/export/${PROJECT_NAME}_pfm/sw/${PROJECT_NAME}_pfm/xrt/image/ >> $ABS_PATH/cmd.log
# Ensure boot/ directory exists before copying the BIF template.
mkdir -p $ABS_PATH/xpfm/${PROJECT_NAME}_pfm/export/${PROJECT_NAME}_pfm/sw/${PROJECT_NAME}_pfm/boot/ >> $ABS_PATH/cmd.log
cp -f $ABS_PATH/a70/xrt/linux.bif      $ABS_PATH/xpfm/${PROJECT_NAME}_pfm/export/${PROJECT_NAME}_pfm/sw/${PROJECT_NAME}_pfm/boot/ >> $ABS_PATH/cmd.log
if [ $? != 0 ]; then tail $ABS_PATH/cmd.log && exit 1; fi

