#+----------------------------------------------------------------------------
#| Vitis Makefile- Developed using new makefile code
#| This make file is generated when the test is run
#| Generated: 2024-04-21 14:14:48.332143
#+----------------------------------------------------------------------------
# Target and command definitions
SHELL = /bin/bash
RM = rm -rf

SRC_TAIL=$(VAISW_HOME)/npu_ip/$(NPU_TAIL)

# Primary build targets
.PHONY: all clean cleanall

all:
	[ -z "$${NPU_TAIL}" ] || cp -r $(SRC_TAIL) ./

clean:
	$(RM) $(NPU_TAIL)
	[ -z "$${NPU_TAIL}" ] ||  $(RM) $(SRC_TAIL)
