#!/bin/bash
#
# Copyright (C) 2025, Advanced Micro Devices, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file is automatically generated using the do script
set -o pipefail
ABS_PATH=$(pwd)
export PROJECT_NAME=example_design

#Production Board
export BOARD=XIL_VEK385
export CHIP_PART=xc2ve3858-ssva2112-2MP-e-S

# Build switches (FMC_CARD, NPU_FW, MIPI) come from rev-b/build.cfg, the shared
# source of truth. build.cfg is authoritative: when present, its values win over
# any inherited/exported environment values. Environment values are used only as
# a fallback when build.cfg is missing (or omits a key); hardcoded defaults apply
# otherwise.
BUILD_CFG="$ABS_PATH/../build.cfg"
if [ -f "$BUILD_CFG" ]; then
  source "$BUILD_CFG"
fi
export FMC_CARD=${FMC_CARD:-96716A}
export NPU_FW=${NPU_FW:-0}
export MIPI=${MIPI:-0}

# NPU_FW is not supported for this release.
if [ "${NPU_FW}" -eq 1 ]; then
  echo "ERROR: NPU_FW=1 is not supported for this release. Exiting." >&2
  exit 1
fi

echo -e "\n # Hardware platform generation has started at: $(date '+%Y-%m-%d %H:%M:%S')"
echo -e " Detailed Vivado logs are available at: ${ABS_PATH}/vivado.log"
if [ "${MIPI}" -eq 1 ]; then
  echo -e " Estimated build duration: ~2 hours\n"
else
  echo -e " Estimated build duration: ~40 minutes\n"
fi

vivado -mode tcl -source create_platform.tcl >> $ABS_PATH/cmd.log
if [ $? != 0 ]; then tail $ABS_PATH/cmd.log && exit 1; fi

echo " # Hardware platform generation completed at: $(date '+%Y-%m-%d %H:%M:%S')"
